package af.settings;

/**
 * This enum provides properties that are to be loaded via
 * XML files to be used for setting up the application.
 * 
 * @author Richard McKenna, Zhenquan Ma
 * @version 1.0
 */
public enum AppPropertyType {
    // LOADED FROM app_properties.xml

    // INITIAL WINDOW TITLE AND LOGO
    APP_TITLE,
    APP_LOGO,
    
    // FOR FINDING THE CSS FILE
    APP_CSS,
    APP_PATH_CSS,

    // FILE TOOLBAR ICONS
    NEW_ICON,
    LOAD_ICON,
    SAVE_ICON,
    SAVE_AS_ICON,
    EXPORT_ICON,
    EXIT_ICON,
    UNDO_ICON,
    REDO_ICON,
    ABOUT_ICON,
        
    // FILE TOOLBAR TOOLTIPS FOR BUTTONS
    NEW_TOOLTIP,
    LOAD_TOOLTIP,
    SAVE_TOOLTIP,
    SAVE_AS_TOOLTIP,
    EXPORT_TOOLTIP,
    EXIT_TOOLTIP,
    UNDO_TOOLTIP,
    REDO_TOOLTIP,
    ABOUT_TOOLTIP,
	
    // ERROR MESSAGES AND TITLES FOR DIALOG BOXES
    NEW_ERROR_MESSAGE,
    NEW_ERROR_TITLE,
    LOAD_ERROR_MESSAGE,
    LOAD_ERROR_TITLE,
    SAVE_ERROR_MESSAGE,
    SAVE_ERROR_TITLE,
    PROPERTIES_LOAD_ERROR_MESSAGE,
    PROPERTIES_LOAD_ERROR_TITLE,
    EXPORT_ERROR_TITLE,
    EXPORT_ERROR_MESSAGE,
    EXPORT_COMPLETED_TITLE,
    EXPORT_COMPLETED_MESSAGE,
    TIME_SLOT_ERROR_TITLE,
    TIME_SLOT_ERROR_MESSAGE,
    EXPORT_DIRECTORY_EMPTY_TITLE,
    EXPORT_DIRECTORY_EMPTY_MESSAGE,
    
	
    // AND VERIFICATION MESSAGES AND TITLES
    NEW_COMPLETED_MESSAGE,
    NEW_COMPLETED_TITLE,
    LOAD_COMPLETED_MESSAGE,
    LOAD_COMPLETED_TITLE,
    SAVE_COMPLETED_MESSAGE,
    SAVE_COMPLETED_TITLE,	
    SAVE_UNSAVED_WORK_TITLE,
    SAVE_UNSAVED_WORK_MESSAGE,
    SAVE_WORK_TITLE,
    LOAD_WORK_TITLE,
    EXPORT_WORK_TITLE,
    EXPORT_WORK_MESSAGE,
    TIMESLOT_VERIFICATION_TITLE,
    TIMESLOT_VERIFICATION_MESSAGE,

    // DATA FILE EXTENSIONS AND DESSCRIPTIONS
    WORK_FILE_EXT,
    WORK_FILE_EXT_DESC,
    PNG_FILE_EXT,
    JPG_FILE_EXT,
    IMAGE_FILE_EXT_DESC,
    
    //ABOUT
    ABOUT_DIALOG_TITLE,
    ABOUT_DIALOG_MESSAGE
}
